name: Deploy
on: [push]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: my-bots.ru
        username: root
        password: ${{ secrets.PASSWORD }}
        script: cd apps/AdminHelperBot/ && git pull && dcu && dcl
